spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/rent_car_microservice_vehicle_db
    username: postgres
    password: 1568996
    driverClassName: org.postgresql.Driver
