server:
  port: 9191
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/rent_car_microservice_customer_db
    username: postgres
    password: 1568996
    driverClassName: org.postgresql.Driver
  
