server:
  port: 9193
spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/rent_car_microservice_rent_db
    username: postgres
    password: 1568996
    driverClassName: org.postgresql.Driver
    
